# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CPC 20791 SW.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setStyleSheet("/* ============================================\n"
"   LIGHT & AIRY THEME with Inter Font\n"
"   Blue Accents\n"
"   ============================================ */\n"
"\n"
"* {\n"
"    font-family: \'Inter\', \'Segoe UI\', \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* ========== ГЛАВНОЕ ОКНО ========== */\n"
"QMainWindow, QDialog, QWidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #fafcff,  /* Чистый светлый */\n"
"                               stop:1 #f0f4fa);  /* Нежный голубоватый */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background: white;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 0 16px 16px 16px;\n"
"    padding: 24px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTabBar {\n"
"    background: transparent;\n"
"    qproperty-drawBase: 0;\n"
"    qproperty-expanding: 0;  /* Запрещаем растягивание */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #f5f9ff,\n"
"                               stop:1 #e9f0f7);\n"
"    color: #4a5b68;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    \n"
"    /* ВАЖНО: минимальная ширина и отступы */\n"
"    min-width:100px;         /* Минимальная ширина */\n"
"    max-width: 200px;        /* Максимальная ширина (можно увеличить) */\n"
"    padding: 10px 20px;      /* Уменьшил горизонтальные отступы */\n"
"    margin-right: 2px;\n"
"    \n"
"    border: none;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    \n"
"    /* Чтобы текст не обрезался и переносился */\n"
"    word-wrap: break-word;\n"
"    white-space: nowrap;     /* Запрещаем перенос */\n"
"}\n"
"\n"
"/* Для очень длинных текстов - разрешаем перенос */\n"
"QTabBar::tab[longtext=\"true\"] {\n"
"    white-space: normal;     /* Разрешаем перенос */\n"
"    min-width: 60px;\n"
"    max-width: 150px;\n"
"    padding: 10px 12px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #ffffff,\n"
"                               stop:1 #f5f9ff);\n"
"    color: #3498db;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"    color: #2980b9;\n"
"    font-weight: 600;\n"
"    border-bottom: 3px solid #3498db;\n"
"    margin-bottom: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:first {\n"
"    margin-left: 20px;\n"
"}\n"
"\n"
"QTabBar::tab:last {\n"
"    margin-right: 0;\n"
"}\n"
"/* ========== GROUP BOX = ИСПРАВЛЕННАЯ ВЕРСИЯ ========== */\n"
"QGroupBox {\n"
"    background: white;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 16px;\n"
"    margin-top: 16px;        /* Уменьшил, чтобы шапка не обрезалась */\n"
"    padding-top: 24px;       /* Увеличил, чтобы дать место для заголовка */\n"
"    padding-bottom: 16px;\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    color: #2c3e50;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: padding;  /* МЕНЯЕМ с margin на padding */\n"
"    subcontrol-position: top left;\n"
"    left: 16px;\n"
"    top: -12px;                 /* Отрицательный отступ поднимает заголовок */\n"
"    padding: 4px 16px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #3498db,\n"
"                               stop:1 #2980b9);\n"
"    border-radius: 20px;\n"
"    border: none;\n"
"    color: white;\n"
"    font-size: 11px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.3px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"/* Альтернативный вариант - заголовок СВЕРХУ (без наложения) */\n"
"QGroupBox#top_title {\n"
"    margin-top: 0px;\n"
"    padding-top: 32px;\n"
"}\n"
"\n"
"QGroupBox#top_title::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top center;  /* По центру */\n"
"    top: -16px;                      /* Чуть выше границы */\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"/* Альтернативный вариант - заголовок ВНУТРИ (слева) */\n"
"QGroupBox#inside_title {\n"
"    margin-top: 0px;\n"
"    padding-top: 16px;\n"
"}\n"
"\n"
"QGroupBox#inside_title::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    left: 16px;\n"
"    top: -8px;                     /* Меньше отступ */\n"
"    padding: 3px 12px;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"/* ========== RADIO BUTTON ========== */\n"
"QRadioButton {\n"
"    color: #2c3e50;\n"
"    font-size: 13px;\n"
"    spacing: 12px;\n"
"    padding: 6px 4px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #d0d9e4;\n"
"    background: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #74b9ff;  /* Светлый голубой */\n"
"    background: #f8fcff;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid #3498db;  /* Голубой */\n"
"    background: qradialgradient(cx:0.5, cy:0.5, radius:0.6,\n"
"                                fx:0.5, fy:0.5,\n"
"                                stop:0 #74b9ff,\n"
"                                stop:0.7 #3498db,\n"
"                                stop:1 #2980b9);\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    color: #1a2634;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* ========== PUSH BUTTON ========== */\n"
"QPushButton {\n"
"    background: white;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #d8e1ec;\n"
"    border-radius: 10px;\n"
"    padding: 10px 24px;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    letter-spacing: 0.2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #f0f8ff,\n"
"                               stop:1 #e5f0ff);\n"
"    border: 1px solid #3498db;  /* Голубой */\n"
"    color: #2980b9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #e5f0ff,\n"
"                               stop:1 #d8eaff);\n"
"    padding-top: 11px;\n"
"    padding-bottom: 9px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #f8fafc;\n"
"    color: #a0b3c2;\n"
"    border: 1px solid #e6ecf5;\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #3498db,   /* Голубой */\n"
"                               stop:1 #2980b9);  /* Тёмный голубой */\n"
"    border: none;\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:default:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #5dade2,\n"
"                               stop:1 #3498db);\n"
"}\n"
"\n"
"/* ========== LABEL ========== */\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    background: transparent;\n"
"    padding: 2px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLabel#title {\n"
"    color: #1a2634;\n"
"    font-size: 20px;\n"
"    font-weight: 700;\n"
"    letter-spacing: -0.3px;\n"
"    padding-bottom: 12px;\n"
"}\n"
"\n"
"QLabel#header {\n"
"    color: #3498db;  /* Голубой */\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"    padding: 8px 0;\n"
"}\n"
"\n"
"QLabel#value {\n"
"    color: #2980b9;  /* Тёмный голубой */\n"
"    font-weight: 700;\n"
"    font-size: 17px;\n"
"    background: #f0f8ff;\n"
"    padding: 6px 16px;\n"
"    border-radius: 24px;\n"
"    border: 1px solid #d4e6f1;\n"
"}\n"
"\n"
"QLabel#accent {\n"
"    color: #3498db;  /* Голубой */\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QLabel#info {\n"
"    color: #7f8c8d;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* ========== LCD NUMBER ========== */\n"
"QLCDNumber {\n"
"    background: white;\n"
"    color: #1a2634;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QLCDNumber#big {\n"
"    font-size: 28px;\n"
"    min-height: 60px;\n"
"    max-height: 80px;\n"
"    color: #2980b9;  /* Голубой */\n"
"    border: 2px solid #3498db;\n"
"}\n"
"\n"
"/* ========== TOOLTIPS ========== */\n"
"QToolTip {\n"
"    background: #2c3e50;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px 16px;\n"
"    font-size: 12px;\n"
"    font-family: \'Inter\', \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"/* ========== SCROLL BARS ========== */\n"
"QScrollBar:vertical {\n"
"    background: #f5f9ff;\n"
"    width: 14px;\n"
"    border-radius: 7px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #cbd5e0;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #3498db;  /* Голубой */\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: #f5f9ff;\n"
"    height: 14px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #cbd5e0;\n"
"    min-width: 30px;\n"
"    border-radius: 7px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #3498db;  /* Голубой */\n"
"}\n"
"\n"
"/* ========== COMBOBOX ========== */\n"
"QComboBox {\n"
"    background: white;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #d8e1ec;\n"
"    border-radius: 10px;\n"
"    padding: 10px 16px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #3498db;  /* Голубой */\n"
"    background: #f0f8ff;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #2980b9;\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #d8e1ec;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #3498db;  /* Голубой */\n"
"    width: 0;\n"
"    height: 0;\n"
"    margin-right: 8px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: white;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #d8e1ec;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #e1f0fa;\n"
"    selection-color: #2980b9;\n"
"    outline: 0;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* ========== LINE EDIT ========== */\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background: white;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #d8e1ec;\n"
"    border-radius: 10px;\n"
"    padding: 10px 14px;\n"
"    font-size: 13px;\n"
"    selection-background-color: #d4e6f1;\n"
"    selection-color: #1a2634;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {\n"
"    border: 1px solid #3498db;  /* Голубой */\n"
"    background: #fafcff;\n"
"}\n"
"\n"
"QLineEdit:hover, QTextEdit:hover, QPlainTextEdit:hover {\n"
"    border: 1px solid #74b9ff;  /* Светлый голубой */\n"
"}\n"
"\n"
"/* ========== CHECKBOX ========== */\n"
"QCheckBox {\n"
"    color: #2c3e50;\n"
"    font-size: 13px;\n"
"    spacing: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 6px;\n"
"    border: 2px solid #d0d9e4;\n"
"    background: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #74b9ff;  /* Светлый голубой */\n"
"    background: #f0f8ff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #3498db,  /* Голубой */\n"
"                               stop:1 #2980b9);\n"
"    border: 2px solid #3498db;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    color: #1a2634;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* ========== SPINBOX ========== */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background: white;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #d8e1ec;\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QSpinBox:hover, QDoubleSpinBox:hover {\n"
"    border: 1px solid #3498db;  /* Голубой */\n"
"}\n"
"\n"
"QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border: 1px solid #2980b9;\n"
"}\n"
"\n"
"/* ========== PROGRESS BAR ========== */\n"
"QProgressBar {\n"
"    background: #edf2f7;\n"
"    border: 1px solid #d8e1ec;\n"
"    border-radius: 10px;\n"
"    height: 24px;\n"
"    text-align: center;\n"
"    color: #2c3e50;\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #74b9ff,  /* Светлый голубой */\n"
"                               stop:1 #3498db);  /* Голубой */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* ========== SLIDER ========== */\n"
"QSlider::groove:horizontal {\n"
"    background: #edf2f7;\n"
"    border: 1px solid #d8e1ec;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #ffffff,\n"
"                               stop:1 #f5f9ff);\n"
"    border: 2px solid #3498db;  /* Голубой */\n"
"    width: 22px;\n"
"    height: 22px;\n"
"    margin: -7px 0;\n"
"    border-radius: 11px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #74b9ff,\n"
"                               stop:1 #3498db);\n"
"    border: 2px solid #2980b9;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #74b9ff,  /* Светлый голубой */\n"
"                               stop:1 #3498db);  /* Голубой */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* ========== TABLE VIEW ========== */\n"
"QTableView {\n"
"    background: white;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"    gridline-color: #edf2f7;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #f0f4fa;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background: #e1f0fa;\n"
"    color: #2980b9;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #f5f9ff;\n"
"    color: #2c3e50;\n"
"    border: none;\n"
"    border-bottom: 2px solid #3498db;  /* Голубой */\n"
"    padding: 12px;\n"
"    font-weight: 600;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* ========== LIST VIEW ========== */\n"
"QListView {\n"
"    background: white;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QListView::item {\n"
"    padding: 10px 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background: #f0f8ff;\n"
"    color: #2980b9;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background: #3498db;  /* Голубой */\n"
"    color: white;\n"
"}\n"
"\n"
"/* ========== MENU BAR ========== */\n"
"QMenuBar {\n"
"    background: white;\n"
"    border-bottom: 1px solid #e6ecf5;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    color: #2c3e50;\n"
"    padding: 10px 18px;\n"
"    border-radius: 8px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #f0f8ff;\n"
"    color: #3498db;\n"
"}\n"
"\n"
"QMenu {\n"
"    background: white;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 10px 28px;\n"
"    border-radius: 8px;\n"
"    color: #2c3e50;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background: #f0f8ff;\n"
"    color: #3498db;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #e6ecf5;\n"
"    margin: 8px 16px;\n"
"}\n"
"\n"
"/* ========== STATUS BAR ========== */\n"
"QStatusBar {\n"
"    background: white;\n"
"    border-top: 1px solid #e6ecf5;\n"
"    color: #7f8c8d;\n"
"    padding: 8px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* ========== SPLITTER ========== */\n"
"QSplitter::handle {\n"
"    background: #e6ecf5;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background: #3498db;  /* Голубой */\n"
"}\n"
"\n"
"/* ========== LIST WIDGET ========== */\n"
"QListWidget {\n"
"    background: white;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 10px 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: #f0f8ff;\n"
"    color: #2980b9;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"/* ========== TREE VIEW ========== */\n"
"QTreeView {\n"
"    background: white;\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    padding: 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QTreeView::item:hover {\n"
"    background: #f0f8ff;\n"
"}\n"
"\n"
"QTreeView::item:selected {\n"
"    background: #e1f0fa;\n"
"    color: #2980b9;\n"
"}\n"
"\n"
"/* ========== TAB BAR (дополнительно) ========== */\n"
"QTabBar::close-button {\n"
"    image: none;\n"
"    background: #e6ecf5;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background: #ff6b6b;\n"
"    color: white;\n"
"}\n"
"\n"
"/* ========== SCROLL AREA ========== */\n"
"QScrollArea {\n"
"    border: 1px solid #e6ecf5;\n"
"    border-radius: 12px;\n"
"    background: white;\n"
"}\n"
"\n"
"/* ========== DATE EDIT ========== */\n"
"QDateEdit {\n"
"    background: white;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #d8e1ec;\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 1px solid #2980b9;\n"
"}\n"
"\n"
"/* ========== DIAL ========== */\n"
"QDial {\n"
"    background: transparent;\n"
"    color: #3498db;\n"
"}\n"
"\n"
"QDial::handle {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #ffffff,\n"
"                               stop:1 #f0f8ff);\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QDial::handle:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #74b9ff,\n"
"                               stop:1 #3498db);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1901, 991))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(22, 40, 1781, 251))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.LDG_GEAR_NORM_0 = QtWidgets.QRadioButton(self.widget)
        self.LDG_GEAR_NORM_0.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.LDG_GEAR_NORM_0.setFont(font)
        self.LDG_GEAR_NORM_0.setCheckable(True)
        self.LDG_GEAR_NORM_0.setChecked(False)
        self.LDG_GEAR_NORM_0.setObjectName("LDG_GEAR_NORM_0")
        self.verticalLayout.addWidget(self.LDG_GEAR_NORM_0)
        self.LDG_GEAR_NORM_1 = QtWidgets.QRadioButton(self.widget)
        self.LDG_GEAR_NORM_1.setCheckable(True)
        self.LDG_GEAR_NORM_1.setObjectName("LDG_GEAR_NORM_1")
        self.verticalLayout.addWidget(self.LDG_GEAR_NORM_1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.LDG_GEAR_ESS_0 = QtWidgets.QRadioButton(self.widget)
        self.LDG_GEAR_ESS_0.setCheckable(True)
        self.LDG_GEAR_ESS_0.setObjectName("LDG_GEAR_ESS_0")
        self.verticalLayout_2.addWidget(self.LDG_GEAR_ESS_0)
        self.LDG_GEAR_ESS_1 = QtWidgets.QRadioButton(self.widget)
        self.LDG_GEAR_ESS_1.setCheckable(True)
        self.LDG_GEAR_ESS_1.setObjectName("LDG_GEAR_ESS_1")
        self.verticalLayout_2.addWidget(self.LDG_GEAR_ESS_1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.MANUAL_MODE_0 = QtWidgets.QRadioButton(self.widget)
        self.MANUAL_MODE_0.setCheckable(True)
        self.MANUAL_MODE_0.setObjectName("MANUAL_MODE_0")
        self.verticalLayout_3.addWidget(self.MANUAL_MODE_0)
        self.MANUAL_MODE_1 = QtWidgets.QRadioButton(self.widget)
        self.MANUAL_MODE_1.setCheckable(True)
        self.MANUAL_MODE_1.setObjectName("MANUAL_MODE_1")
        self.verticalLayout_3.addWidget(self.MANUAL_MODE_1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.DITCH_SWITCH_0 = QtWidgets.QRadioButton(self.widget)
        self.DITCH_SWITCH_0.setCheckable(True)
        self.DITCH_SWITCH_0.setObjectName("DITCH_SWITCH_0")
        self.verticalLayout_4.addWidget(self.DITCH_SWITCH_0)
        self.DITCH_SWITCH_1 = QtWidgets.QRadioButton(self.widget)
        self.DITCH_SWITCH_1.setCheckable(True)
        self.DITCH_SWITCH_1.setObjectName("DITCH_SWITCH_1")
        self.verticalLayout_4.addWidget(self.DITCH_SWITCH_1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.EMER_RAM_AIR_0 = QtWidgets.QRadioButton(self.widget)
        self.EMER_RAM_AIR_0.setCheckable(True)
        self.EMER_RAM_AIR_0.setObjectName("EMER_RAM_AIR_0")
        self.verticalLayout_5.addWidget(self.EMER_RAM_AIR_0)
        self.EMER_RAM_AIR_1 = QtWidgets.QRadioButton(self.widget)
        self.EMER_RAM_AIR_1.setCheckable(True)
        self.EMER_RAM_AIR_1.setObjectName("EMER_RAM_AIR_1")
        self.verticalLayout_5.addWidget(self.EMER_RAM_AIR_1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 4, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.RS_SELECT_0 = QtWidgets.QRadioButton(self.widget)
        self.RS_SELECT_0.setCheckable(True)
        self.RS_SELECT_0.setObjectName("RS_SELECT_0")
        self.verticalLayout_6.addWidget(self.RS_SELECT_0)
        self.RS_SELECT_1 = QtWidgets.QRadioButton(self.widget)
        self.RS_SELECT_1.setCheckable(True)
        self.RS_SELECT_1.setObjectName("RS_SELECT_1")
        self.verticalLayout_6.addWidget(self.RS_SELECT_1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 5, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.FMS_ENABLE_0 = QtWidgets.QRadioButton(self.widget)
        self.FMS_ENABLE_0.setCheckable(True)
        self.FMS_ENABLE_0.setObjectName("FMS_ENABLE_0")
        self.verticalLayout_7.addWidget(self.FMS_ENABLE_0)
        self.FMS_ENABLE_1 = QtWidgets.QRadioButton(self.widget)
        self.FMS_ENABLE_1.setCheckable(True)
        self.FMS_ENABLE_1.setObjectName("FMS_ENABLE_1")
        self.verticalLayout_7.addWidget(self.FMS_ENABLE_1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 6, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_13.addWidget(self.label_28)
        self.FAULT_WARN_WR_0 = QtWidgets.QRadioButton(self.widget)
        self.FAULT_WARN_WR_0.setCheckable(True)
        self.FAULT_WARN_WR_0.setObjectName("FAULT_WARN_WR_0")
        self.verticalLayout_13.addWidget(self.FAULT_WARN_WR_0)
        self.FAULT_WARN_WR_1 = QtWidgets.QRadioButton(self.widget)
        self.FAULT_WARN_WR_1.setCheckable(True)
        self.FAULT_WARN_WR_1.setObjectName("FAULT_WARN_WR_1")
        self.verticalLayout_13.addWidget(self.FAULT_WARN_WR_1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15)
        self.gridLayout.addLayout(self.verticalLayout_13, 1, 5, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_12.addWidget(self.label_27)
        self.SYS_IN_CNTL_IN_0 = QtWidgets.QRadioButton(self.widget)
        self.SYS_IN_CNTL_IN_0.setCheckable(True)
        self.SYS_IN_CNTL_IN_0.setObjectName("SYS_IN_CNTL_IN_0")
        self.verticalLayout_12.addWidget(self.SYS_IN_CNTL_IN_0)
        self.SYS_IN_CNTL_IN_1 = QtWidgets.QRadioButton(self.widget)
        self.SYS_IN_CNTL_IN_1.setCheckable(True)
        self.SYS_IN_CNTL_IN_1.setObjectName("SYS_IN_CNTL_IN_1")
        self.verticalLayout_12.addWidget(self.SYS_IN_CNTL_IN_1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.gridLayout.addLayout(self.verticalLayout_12, 1, 4, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_11.addWidget(self.label_26)
        self.HI_CRFL_0 = QtWidgets.QRadioButton(self.widget)
        self.HI_CRFL_0.setCheckable(True)
        self.HI_CRFL_0.setObjectName("HI_CRFL_0")
        self.verticalLayout_11.addWidget(self.HI_CRFL_0)
        self.HI_CRFL_1 = QtWidgets.QRadioButton(self.widget)
        self.HI_CRFL_1.setCheckable(True)
        self.HI_CRFL_1.setObjectName("HI_CRFL_1")
        self.verticalLayout_11.addWidget(self.HI_CRFL_1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.gridLayout.addLayout(self.verticalLayout_11, 1, 3, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_10.addWidget(self.label_25)
        self.ENG2_N2_1 = QtWidgets.QRadioButton(self.widget)
        self.ENG2_N2_1.setCheckable(True)
        self.ENG2_N2_1.setObjectName("ENG2_N2_1")
        self.verticalLayout_10.addWidget(self.ENG2_N2_1)
        self.ENG2_N2_2 = QtWidgets.QRadioButton(self.widget)
        self.ENG2_N2_2.setCheckable(True)
        self.ENG2_N2_2.setObjectName("ENG2_N2_2")
        self.verticalLayout_10.addWidget(self.ENG2_N2_2)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.gridLayout.addLayout(self.verticalLayout_10, 1, 2, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_9.addWidget(self.label_24)
        self.ENG1_N2_0 = QtWidgets.QRadioButton(self.widget)
        self.ENG1_N2_0.setCheckable(True)
        self.ENG1_N2_0.setObjectName("ENG1_N2_0")
        self.verticalLayout_9.addWidget(self.ENG1_N2_0)
        self.ENG1_N2_1 = QtWidgets.QRadioButton(self.widget)
        self.ENG1_N2_1.setCheckable(True)
        self.ENG1_N2_1.setObjectName("ENG1_N2_1")
        self.verticalLayout_9.addWidget(self.ENG1_N2_1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.gridLayout.addLayout(self.verticalLayout_9, 1, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_8.addWidget(self.label_23)
        self.SYS_ID_0 = QtWidgets.QRadioButton(self.widget)
        self.SYS_ID_0.setCheckable(True)
        self.SYS_ID_0.setObjectName("SYS_ID_0")
        self.verticalLayout_8.addWidget(self.SYS_ID_0)
        self.SYS_ID_1 = QtWidgets.QRadioButton(self.widget)
        self.SYS_ID_1.setCheckable(True)
        self.SYS_ID_1.setObjectName("SYS_ID_1")
        self.verticalLayout_8.addWidget(self.SYS_ID_1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.sys_in_ctrl_no = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.sys_in_ctrl_no.setFont(font)
        self.sys_in_ctrl_no.setCheckable(True)
        self.sys_in_ctrl_no.setChecked(False)
        self.sys_in_ctrl_no.setObjectName("sys_in_ctrl_no")
        self.verticalLayout_16.addWidget(self.sys_in_ctrl_no)
        self.sys_in_ctrl_yes = QtWidgets.QRadioButton(self.groupBox_2)
        self.sys_in_ctrl_yes.setCheckable(True)
        self.sys_in_ctrl_yes.setObjectName("sys_in_ctrl_yes")
        self.verticalLayout_16.addWidget(self.sys_in_ctrl_yes)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_16.addWidget(self.label_31)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.sys_status_good = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.sys_status_good.setFont(font)
        self.sys_status_good.setCheckable(True)
        self.sys_status_good.setChecked(False)
        self.sys_status_good.setObjectName("sys_status_good")
        self.verticalLayout_26.addWidget(self.sys_status_good)
        self.sys_status_fail = QtWidgets.QRadioButton(self.groupBox_2)
        self.sys_status_fail.setCheckable(True)
        self.sys_status_fail.setObjectName("sys_status_fail")
        self.verticalLayout_26.addWidget(self.sys_status_fail)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_26.addWidget(self.label_32)
        self.horizontalLayout_2.addLayout(self.verticalLayout_26)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.lfe_from_fms_used = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lfe_from_fms_used.setFont(font)
        self.lfe_from_fms_used.setCheckable(True)
        self.lfe_from_fms_used.setChecked(False)
        self.lfe_from_fms_used.setObjectName("lfe_from_fms_used")
        self.verticalLayout_25.addWidget(self.lfe_from_fms_used)
        self.lfe_from_fms_nused = QtWidgets.QRadioButton(self.groupBox_2)
        self.lfe_from_fms_nused.setCheckable(True)
        self.lfe_from_fms_nused.setObjectName("lfe_from_fms_nused")
        self.verticalLayout_25.addWidget(self.lfe_from_fms_nused)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_25.addWidget(self.label_33)
        self.horizontalLayout_2.addLayout(self.verticalLayout_25)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.cabine_altitude_nwarn = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cabine_altitude_nwarn.setFont(font)
        self.cabine_altitude_nwarn.setCheckable(True)
        self.cabine_altitude_nwarn.setChecked(False)
        self.cabine_altitude_nwarn.setObjectName("cabine_altitude_nwarn")
        self.verticalLayout_24.addWidget(self.cabine_altitude_nwarn)
        self.cabine_altitude_warn = QtWidgets.QRadioButton(self.groupBox_2)
        self.cabine_altitude_warn.setCheckable(True)
        self.cabine_altitude_warn.setObjectName("cabine_altitude_warn")
        self.verticalLayout_24.addWidget(self.cabine_altitude_warn)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_24.addWidget(self.label_34)
        self.horizontalLayout_2.addLayout(self.verticalLayout_24)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.diff_pressure_nwarn = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.diff_pressure_nwarn.setFont(font)
        self.diff_pressure_nwarn.setCheckable(True)
        self.diff_pressure_nwarn.setChecked(False)
        self.diff_pressure_nwarn.setObjectName("diff_pressure_nwarn")
        self.verticalLayout_23.addWidget(self.diff_pressure_nwarn)
        self.diff_pressure_warn = QtWidgets.QRadioButton(self.groupBox_2)
        self.diff_pressure_warn.setCheckable(True)
        self.diff_pressure_warn.setObjectName("diff_pressure_warn")
        self.verticalLayout_23.addWidget(self.diff_pressure_warn)
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_23.addWidget(self.label_39)
        self.horizontalLayout_2.addLayout(self.verticalLayout_23)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.preplanned_good = QtWidgets.QCheckBox(self.groupBox_2)
        self.preplanned_good.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.preplanned_good.setFont(font)
        self.preplanned_good.setMouseTracking(True)
        self.preplanned_good.setCheckable(True)
        self.preplanned_good.setChecked(False)
        self.preplanned_good.setObjectName("preplanned_good")
        self.verticalLayout_18.addWidget(self.preplanned_good)
        self.preplanned_toofast = QtWidgets.QCheckBox(self.groupBox_2)
        self.preplanned_toofast.setCheckable(True)
        self.preplanned_toofast.setObjectName("preplanned_toofast")
        self.verticalLayout_18.addWidget(self.preplanned_toofast)
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_18.addWidget(self.label_40)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        self.verticalLayout_30.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.lfes_stat_auto = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lfes_stat_auto.setFont(font)
        self.lfes_stat_auto.setCheckable(True)
        self.lfes_stat_auto.setChecked(False)
        self.lfes_stat_auto.setObjectName("lfes_stat_auto")
        self.verticalLayout_28.addWidget(self.lfes_stat_auto)
        self.lfes_stat_manual = QtWidgets.QRadioButton(self.groupBox_2)
        self.lfes_stat_manual.setCheckable(True)
        self.lfes_stat_manual.setObjectName("lfes_stat_manual")
        self.verticalLayout_28.addWidget(self.lfes_stat_manual)
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_28.addWidget(self.label_41)
        self.horizontalLayout_3.addLayout(self.verticalLayout_28)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.adirs_ch_no = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.adirs_ch_no.setFont(font)
        self.adirs_ch_no.setCheckable(True)
        self.adirs_ch_no.setChecked(False)
        self.adirs_ch_no.setObjectName("adirs_ch_no")
        self.verticalLayout_27.addWidget(self.adirs_ch_no)
        self.adirs_ch_1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.adirs_ch_1.setCheckable(True)
        self.adirs_ch_1.setObjectName("adirs_ch_1")
        self.verticalLayout_27.addWidget(self.adirs_ch_1)
        self.adirs_ch_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.adirs_ch_2.setCheckable(True)
        self.adirs_ch_2.setObjectName("adirs_ch_2")
        self.verticalLayout_27.addWidget(self.adirs_ch_2)
        self.adirs_ch_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.adirs_ch_3.setCheckable(True)
        self.adirs_ch_3.setObjectName("adirs_ch_3")
        self.verticalLayout_27.addWidget(self.adirs_ch_3)
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_27.addWidget(self.label_42)
        self.horizontalLayout_3.addLayout(self.verticalLayout_27)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.fms_disable = QtWidgets.QCheckBox(self.groupBox_2)
        self.fms_disable.setCheckable(True)
        self.fms_disable.setObjectName("fms_disable")
        self.verticalLayout_22.addWidget(self.fms_disable)
        self.fms_enable = QtWidgets.QCheckBox(self.groupBox_2)
        self.fms_enable.setCheckable(True)
        self.fms_enable.setObjectName("fms_enable")
        self.verticalLayout_22.addWidget(self.fms_enable)
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_22.addWidget(self.label_43)
        self.horizontalLayout_3.addLayout(self.verticalLayout_22)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.flight_modes_gr = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.flight_modes_gr.setFont(font)
        self.flight_modes_gr.setCheckable(True)
        self.flight_modes_gr.setChecked(False)
        self.flight_modes_gr.setObjectName("flight_modes_gr")
        self.verticalLayout_20.addWidget(self.flight_modes_gr)
        self.flight_modes_to = QtWidgets.QCheckBox(self.groupBox_2)
        self.flight_modes_to.setCheckable(True)
        self.flight_modes_to.setObjectName("flight_modes_to")
        self.verticalLayout_20.addWidget(self.flight_modes_to)
        self.flight_modes_ci = QtWidgets.QCheckBox(self.groupBox_2)
        self.flight_modes_ci.setCheckable(True)
        self.flight_modes_ci.setObjectName("flight_modes_ci")
        self.verticalLayout_20.addWidget(self.flight_modes_ci)
        self.flight_modes_ce = QtWidgets.QCheckBox(self.groupBox_2)
        self.flight_modes_ce.setCheckable(True)
        self.flight_modes_ce.setObjectName("flight_modes_ce")
        self.verticalLayout_20.addWidget(self.flight_modes_ce)
        self.horizontalLayout.addLayout(self.verticalLayout_20)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.flight_modes_cr = QtWidgets.QCheckBox(self.groupBox_2)
        self.flight_modes_cr.setCheckable(True)
        self.flight_modes_cr.setObjectName("flight_modes_cr")
        self.verticalLayout_19.addWidget(self.flight_modes_cr)
        self.flight_modes_di = QtWidgets.QCheckBox(self.groupBox_2)
        self.flight_modes_di.setCheckable(True)
        self.flight_modes_di.setObjectName("flight_modes_di")
        self.verticalLayout_19.addWidget(self.flight_modes_di)
        self.flight_modes_de = QtWidgets.QCheckBox(self.groupBox_2)
        self.flight_modes_de.setCheckable(True)
        self.flight_modes_de.setObjectName("flight_modes_de")
        self.verticalLayout_19.addWidget(self.flight_modes_de)
        self.flight_modes_ab = QtWidgets.QCheckBox(self.groupBox_2)
        self.flight_modes_ab.setCheckable(True)
        self.flight_modes_ab.setObjectName("flight_modes_ab")
        self.verticalLayout_19.addWidget(self.flight_modes_ab)
        self.horizontalLayout.addLayout(self.verticalLayout_19)
        self.verticalLayout_21.addLayout(self.horizontalLayout)
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_21.addWidget(self.label_44)
        self.horizontalLayout_3.addLayout(self.verticalLayout_21)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.fms_sel_1eng = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.fms_sel_1eng.setFont(font)
        self.fms_sel_1eng.setCheckable(True)
        self.fms_sel_1eng.setChecked(False)
        self.fms_sel_1eng.setObjectName("fms_sel_1eng")
        self.verticalLayout_14.addWidget(self.fms_sel_1eng)
        self.fms_sel_1neng = QtWidgets.QCheckBox(self.groupBox_2)
        self.fms_sel_1neng.setCheckable(True)
        self.fms_sel_1neng.setObjectName("fms_sel_1neng")
        self.verticalLayout_14.addWidget(self.fms_sel_1neng)
        self.fms_sel_2eng = QtWidgets.QCheckBox(self.groupBox_2)
        self.fms_sel_2eng.setCheckable(True)
        self.fms_sel_2eng.setObjectName("fms_sel_2eng")
        self.verticalLayout_14.addWidget(self.fms_sel_2eng)
        self.fms_sel_2neng = QtWidgets.QCheckBox(self.groupBox_2)
        self.fms_sel_2neng.setCheckable(True)
        self.fms_sel_2neng.setObjectName("fms_sel_2neng")
        self.verticalLayout_14.addWidget(self.fms_sel_2neng)
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_14.addWidget(self.label_45)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_30.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.fms_use_use = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.fms_use_use.setFont(font)
        self.fms_use_use.setCheckable(True)
        self.fms_use_use.setChecked(False)
        self.fms_use_use.setObjectName("fms_use_use")
        self.verticalLayout_29.addWidget(self.fms_use_use)
        self.fms_use_nuse = QtWidgets.QCheckBox(self.groupBox_2)
        self.fms_use_nuse.setCheckable(True)
        self.fms_use_nuse.setObjectName("fms_use_nuse")
        self.verticalLayout_29.addWidget(self.fms_use_nuse)
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_29.addWidget(self.label_46)
        self.horizontalLayout_4.addLayout(self.verticalLayout_29)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.class2fault_pres = QtWidgets.QCheckBox(self.groupBox_2)
        self.class2fault_pres.setCheckable(True)
        self.class2fault_pres.setObjectName("class2fault_pres")
        self.verticalLayout_15.addWidget(self.class2fault_pres)
        self.class2fault_npres = QtWidgets.QCheckBox(self.groupBox_2)
        self.class2fault_npres.setCheckable(True)
        self.class2fault_npres.setObjectName("class2fault_npres")
        self.verticalLayout_15.addWidget(self.class2fault_npres)
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_15.addWidget(self.label_48)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.qnh_use = QtWidgets.QCheckBox(self.groupBox_2)
        self.qnh_use.setCheckable(True)
        self.qnh_use.setObjectName("qnh_use")
        self.verticalLayout_17.addWidget(self.qnh_use)
        self.qnh_nuse = QtWidgets.QCheckBox(self.groupBox_2)
        self.qnh_nuse.setCheckable(True)
        self.qnh_nuse.setObjectName("qnh_nuse")
        self.verticalLayout_17.addWidget(self.qnh_nuse)
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_17.addWidget(self.label_47)
        self.horizontalLayout_4.addLayout(self.verticalLayout_17)
        self.verticalLayout_30.addLayout(self.horizontalLayout_4)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 5)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_88 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_5.addWidget(self.label_88)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.groupBox_10)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.horizontalLayout_5.addWidget(self.lcdNumber_7)
        self.label_89 = QtWidgets.QLabel(self.groupBox_10)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout_5.addWidget(self.label_89)
        self.verticalLayout_31.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_90 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_6.addWidget(self.label_90)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.groupBox_10)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.horizontalLayout_6.addWidget(self.lcdNumber_8)
        self.label_91 = QtWidgets.QLabel(self.groupBox_10)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_6.addWidget(self.label_91)
        self.verticalLayout_31.addLayout(self.horizontalLayout_6)
        self.gridLayout_5.addWidget(self.groupBox_10, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_51 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 0, 0, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_4.addWidget(self.lcdNumber_3, 0, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_6)
        self.label_52.setObjectName("label_52")
        self.gridLayout_4.addWidget(self.label_52, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_3.addWidget(self.lcdNumber, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 2, 2, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sdac_1 = QtWidgets.QRadioButton(self.groupBox_11)
        self.sdac_1.setCheckable(True)
        self.sdac_1.setObjectName("sdac_1")
        self.gridLayout_2.addWidget(self.sdac_1, 0, 0, 1, 1)
        self.sdac_2 = QtWidgets.QRadioButton(self.groupBox_11)
        self.sdac_2.setCheckable(True)
        self.sdac_2.setObjectName("sdac_2")
        self.gridLayout_2.addWidget(self.sdac_2, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_11, 2, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 2, 4, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, "CPC 20791 Out")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 250, 1061, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_53 = QtWidgets.QLabel(self.groupBox_7)
        self.label_53.setGeometry(QtCore.QRect(20, 30, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdNumber_4.setGeometry(QtCore.QRect(170, 20, 64, 31))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.label_54 = QtWidgets.QLabel(self.groupBox_7)
        self.label_54.setGeometry(QtCore.QRect(240, 30, 47, 13))
        self.label_54.setObjectName("label_54")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 10, 1061, 241))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 341, 80))
        self.groupBox.setObjectName("groupBox")
        self.label_57 = QtWidgets.QLabel(self.groupBox)
        self.label_57.setGeometry(QtCore.QRect(10, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox)
        self.label_58.setGeometry(QtCore.QRect(10, 50, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.static_pressure = QtWidgets.QLineEdit(self.groupBox)
        self.static_pressure.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.static_pressure.setObjectName("static_pressure")
        self.true_airspeed = QtWidgets.QLineEdit(self.groupBox)
        self.true_airspeed.setGeometry(QtCore.QRect(180, 50, 113, 20))
        self.true_airspeed.setObjectName("true_airspeed")
        self.label_59 = QtWidgets.QLabel(self.groupBox)
        self.label_59.setGeometry(QtCore.QRect(301, 56, 47, 13))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox)
        self.label_60.setGeometry(QtCore.QRect(301, 28, 47, 13))
        self.label_60.setObjectName("label_60")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_4.setGeometry(QtCore.QRect(360, 60, 681, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_65 = QtWidgets.QLabel(self.groupBox_4)
        self.label_65.setGeometry(QtCore.QRect(10, 20, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_4)
        self.label_66.setGeometry(QtCore.QRect(10, 50, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.utc = QtWidgets.QLineEdit(self.groupBox_4)
        self.utc.setGeometry(QtCore.QRect(309, 20, 113, 20))
        self.utc.setObjectName("utc")
        self.flight_phase = QtWidgets.QLineEdit(self.groupBox_4)
        self.flight_phase.setGeometry(QtCore.QRect(309, 50, 113, 20))
        self.flight_phase.setObjectName("flight_phase")
        self.label_69 = QtWidgets.QLabel(self.groupBox_4)
        self.label_69.setGeometry(QtCore.QRect(10, 80, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_4)
        self.label_70.setGeometry(QtCore.QRect(10, 110, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupBox_4)
        self.label_71.setGeometry(QtCore.QRect(10, 140, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.bite_commands = QtWidgets.QLineEdit(self.groupBox_4)
        self.bite_commands.setGeometry(QtCore.QRect(310, 80, 113, 20))
        self.bite_commands.setObjectName("bite_commands")
        self.date = QtWidgets.QLineEdit(self.groupBox_4)
        self.date.setGeometry(QtCore.QRect(310, 110, 113, 20))
        self.date.setObjectName("date")
        self.aircraft_id = QtWidgets.QLineEdit(self.groupBox_4)
        self.aircraft_id.setGeometry(QtCore.QRect(310, 140, 113, 20))
        self.aircraft_id.setObjectName("aircraft_id")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 150, 341, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_82 = QtWidgets.QLabel(self.groupBox_9)
        self.label_82.setGeometry(QtCore.QRect(10, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.groupBox_9)
        self.label_83.setGeometry(QtCore.QRect(10, 50, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.valid_word_discrete = QtWidgets.QLineEdit(self.groupBox_9)
        self.valid_word_discrete.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.valid_word_discrete.setObjectName("valid_word_discrete")
        self.lfe_in_feet = QtWidgets.QLineEdit(self.groupBox_9)
        self.lfe_in_feet.setGeometry(QtCore.QRect(180, 50, 113, 20))
        self.lfe_in_feet.setObjectName("lfe_in_feet")
        self.label_84 = QtWidgets.QLabel(self.groupBox_9)
        self.label_84.setGeometry(QtCore.QRect(301, 56, 47, 13))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.groupBox_9)
        self.label_85.setGeometry(QtCore.QRect(301, 28, 47, 13))
        self.label_85.setText("")
        self.label_85.setObjectName("label_85")
        self.setDefaultButton = QtWidgets.QPushButton(self.groupBox_8)
        self.setDefaultButton.setGeometry(QtCore.QRect(20, 30, 101, 23))
        self.setDefaultButton.setObjectName("setDefaultButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 44))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "ARINC Label 352 / 353"))
        self.label_16.setText(_translate("MainWindow", "SA3"))
        self.LDG_GEAR_NORM_0.setText(_translate("MainWindow", "Compressed"))
        self.LDG_GEAR_NORM_1.setText(_translate("MainWindow", "Not compressed"))
        self.label.setText(_translate("MainWindow", "LDG_GEAR_NORM"))
        self.label_17.setText(_translate("MainWindow", "SA4"))
        self.LDG_GEAR_ESS_0.setText(_translate("MainWindow", "Compressed"))
        self.LDG_GEAR_ESS_1.setText(_translate("MainWindow", "Not compressed"))
        self.label_2.setText(_translate("MainWindow", "LDG_GEAR_ESS"))
        self.label_18.setText(_translate("MainWindow", "SA5"))
        self.MANUAL_MODE_0.setText(_translate("MainWindow", "AUTO"))
        self.MANUAL_MODE_1.setText(_translate("MainWindow", "MANUAL"))
        self.label_3.setText(_translate("MainWindow", "MANUAL_MODE"))
        self.label_19.setText(_translate("MainWindow", "SA6"))
        self.DITCH_SWITCH_0.setText(_translate("MainWindow", "DITCH"))
        self.DITCH_SWITCH_1.setText(_translate("MainWindow", "NO DITCH"))
        self.label_4.setText(_translate("MainWindow", "DITCH_SWITCH"))
        self.label_20.setText(_translate("MainWindow", "SA7"))
        self.EMER_RAM_AIR_0.setText(_translate("MainWindow", "RAM AIR OFF"))
        self.EMER_RAM_AIR_1.setText(_translate("MainWindow", "RAM AIR ON"))
        self.label_5.setText(_translate("MainWindow", "EMER_RAM_AIR"))
        self.label_21.setText(_translate("MainWindow", "SA8"))
        self.RS_SELECT_0.setText(_translate("MainWindow", "RS232 SELECTED"))
        self.RS_SELECT_1.setText(_translate("MainWindow", "RS422 SELECTED"))
        self.label_6.setText(_translate("MainWindow", "RS_SELECT"))
        self.label_22.setText(_translate("MainWindow", "SA9"))
        self.FMS_ENABLE_0.setText(_translate("MainWindow", "FMS DISABLED"))
        self.FMS_ENABLE_1.setText(_translate("MainWindow", "FMS ENABLED"))
        self.label_7.setText(_translate("MainWindow", "FMS_ENABLE"))
        self.label_28.setText(_translate("MainWindow", "SA19"))
        self.FAULT_WARN_WR_0.setText(_translate("MainWindow", "SYSTEM FAULT"))
        self.FAULT_WARN_WR_1.setText(_translate("MainWindow", "SYSTEM OK"))
        self.label_15.setText(_translate("MainWindow", "FAULT_WARN_WR"))
        self.label_27.setText(_translate("MainWindow", "SA18"))
        self.SYS_IN_CNTL_IN_0.setText(_translate("MainWindow", "SYS NOT IN CONTROL"))
        self.SYS_IN_CNTL_IN_1.setText(_translate("MainWindow", "SYS IN CONTROL"))
        self.label_14.setText(_translate("MainWindow", "SYS_IN_CNTL_IN"))
        self.label_26.setText(_translate("MainWindow", "SA13"))
        self.HI_CRFL_0.setText(_translate("MainWindow", "SELECTED"))
        self.HI_CRFL_1.setText(_translate("MainWindow", "NOT SELECTED"))
        self.label_11.setText(_translate("MainWindow", "HI_CRFL"))
        self.label_25.setText(_translate("MainWindow", "SA12"))
        self.ENG2_N2_1.setText(_translate("MainWindow", "TO POWER"))
        self.ENG2_N2_2.setText(_translate("MainWindow", "NO TO POWER"))
        self.label_10.setText(_translate("MainWindow", "ENG2_N2"))
        self.label_24.setText(_translate("MainWindow", "SA11"))
        self.ENG1_N2_0.setText(_translate("MainWindow", "TO POWER"))
        self.ENG1_N2_1.setText(_translate("MainWindow", "NO TO POWER"))
        self.label_9.setText(_translate("MainWindow", "ENG1_N2"))
        self.label_23.setText(_translate("MainWindow", "SA10"))
        self.SYS_ID_0.setText(_translate("MainWindow", "MASTER"))
        self.SYS_ID_1.setText(_translate("MainWindow", "SLAVE"))
        self.label_8.setText(_translate("MainWindow", "SYS_ID"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ARINC Label 057"))
        self.sys_in_ctrl_no.setText(_translate("MainWindow", "NO"))
        self.sys_in_ctrl_yes.setText(_translate("MainWindow", "YES"))
        self.label_31.setText(_translate("MainWindow", "SYSTEM IN CONTROL"))
        self.sys_status_good.setText(_translate("MainWindow", "GOOD"))
        self.sys_status_fail.setText(_translate("MainWindow", "FAIL"))
        self.label_32.setText(_translate("MainWindow", "SYSTEM STATUS"))
        self.lfe_from_fms_used.setText(_translate("MainWindow", "USED"))
        self.lfe_from_fms_nused.setText(_translate("MainWindow", "NOT USED"))
        self.label_33.setText(_translate("MainWindow", "LFE FROM FMS"))
        self.cabine_altitude_nwarn.setText(_translate("MainWindow", "NO WARN"))
        self.cabine_altitude_warn.setText(_translate("MainWindow", "WARNING"))
        self.label_34.setText(_translate("MainWindow", "EXCESSIVE CABINE ALTITUDE"))
        self.diff_pressure_nwarn.setText(_translate("MainWindow", "NO WARN"))
        self.diff_pressure_warn.setText(_translate("MainWindow", "WARNING"))
        self.label_39.setText(_translate("MainWindow", "LOW DIFFERENTIAL PRESSURE"))
        self.preplanned_good.setText(_translate("MainWindow", "GOOD"))
        self.preplanned_toofast.setText(_translate("MainWindow", "TOO FAST"))
        self.label_40.setText(_translate("MainWindow", "PREPLANNED DESCENT INFO"))
        self.lfes_stat_auto.setText(_translate("MainWindow", "AUTO"))
        self.lfes_stat_manual.setText(_translate("MainWindow", "MANUAL"))
        self.label_41.setText(_translate("MainWindow", "LFES STATUS"))
        self.adirs_ch_no.setText(_translate("MainWindow", "NO ADIRS"))
        self.adirs_ch_1.setText(_translate("MainWindow", "ADIRS 1"))
        self.adirs_ch_2.setText(_translate("MainWindow", "ADIRS 2"))
        self.adirs_ch_3.setText(_translate("MainWindow", "ADIRS 3"))
        self.label_42.setText(_translate("MainWindow", "ADIRS CHANNEL"))
        self.fms_disable.setText(_translate("MainWindow", "FMS DISABLED"))
        self.fms_enable.setText(_translate("MainWindow", "FMS ENABLED"))
        self.label_43.setText(_translate("MainWindow", "FMS_ENABLE"))
        self.flight_modes_gr.setText(_translate("MainWindow", "GR (GROUND)"))
        self.flight_modes_to.setText(_translate("MainWindow", "TO (TAKE OFF)"))
        self.flight_modes_ci.setText(_translate("MainWindow", "CI (CLIMB INTERNAL)"))
        self.flight_modes_ce.setText(_translate("MainWindow", "CE (CLIMB EXTERNAL)"))
        self.flight_modes_cr.setText(_translate("MainWindow", "CR (CRUISE)"))
        self.flight_modes_di.setText(_translate("MainWindow", "DI (DECENT INTERNAL)"))
        self.flight_modes_de.setText(_translate("MainWindow", "DE (DECENT EXTERNAL)"))
        self.flight_modes_ab.setText(_translate("MainWindow", "AB (ABORT)"))
        self.label_44.setText(_translate("MainWindow", "FLIGHT MODES"))
        self.fms_sel_1eng.setText(_translate("MainWindow", "FMS 1  MASTER, AP ENGAGED"))
        self.fms_sel_1neng.setText(_translate("MainWindow", "FMS 1  MASTER, AP NOT ENGAGED"))
        self.fms_sel_2eng.setText(_translate("MainWindow", "FMS 2  MASTER, AP ENGAGED"))
        self.fms_sel_2neng.setText(_translate("MainWindow", "FMS 2  MASTER, AP NOT  ENGAGED"))
        self.label_45.setText(_translate("MainWindow", "FMS SELECTION"))
        self.fms_use_use.setText(_translate("MainWindow", "FMS 1 OR FMS 2 USED AND LABEL 351 VALID"))
        self.fms_use_nuse.setText(_translate("MainWindow", "NO FMS USED"))
        self.label_46.setText(_translate("MainWindow", "FMS USE"))
        self.class2fault_pres.setText(_translate("MainWindow", "PRESENT"))
        self.class2fault_npres.setText(_translate("MainWindow", "NOT PRESENT"))
        self.label_48.setText(_translate("MainWindow", "CLASS 2 FAULT"))
        self.qnh_use.setText(_translate("MainWindow", "USED"))
        self.qnh_nuse.setText(_translate("MainWindow", "NOT USED"))
        self.label_47.setText(_translate("MainWindow", "QNH FROM FMS"))
        self.groupBox_10.setTitle(_translate("MainWindow", "UUT to operator (RS422)"))
        self.label_88.setText(_translate("MainWindow", "PRESSURE"))
        self.label_89.setText(_translate("MainWindow", "hPa"))
        self.label_90.setText(_translate("MainWindow", "ALT CAB RATO"))
        self.label_91.setText(_translate("MainWindow", "hPa / min"))
        self.groupBox_6.setTitle(_translate("MainWindow", "UUT to OFV (RS422)"))
        self.label_51.setText(_translate("MainWindow", "COMMANDED POSITION"))
        self.label_52.setText(_translate("MainWindow", "degrees"))
        self.groupBox_5.setTitle(_translate("MainWindow", "ARINC Label 163"))
        self.label_29.setText(_translate("MainWindow", "LANDING FIELD ELEVATION"))
        self.label_30.setText(_translate("MainWindow", "ft."))
        self.groupBox_11.setTitle(_translate("MainWindow", "SDAC ACTIVITY"))
        self.sdac_1.setText(_translate("MainWindow", "SDAC 1"))
        self.sdac_2.setText(_translate("MainWindow", "SDAC 2"))
        self.pushButton.setText(_translate("MainWindow", "Exit"))
        self.groupBox_7.setTitle(_translate("MainWindow", " OFV to CPC (RS422)"))
        self.label_53.setText(_translate("MainWindow", "CURRENT POSITION"))
        self.label_54.setText(_translate("MainWindow", "degrees"))
        self.groupBox_8.setTitle(_translate("MainWindow", "ARINC to CPC"))
        self.groupBox.setTitle(_translate("MainWindow", "ADIRS"))
        self.label_57.setText(_translate("MainWindow", "Static ambient pressure"))
        self.label_58.setText(_translate("MainWindow", "True airspeed"))
        self.static_pressure.setToolTip(_translate("MainWindow", "E7F80165 default label"))
        self.true_airspeed.setToolTip(_translate("MainWindow", "6C800111 E0C80111 default"))
        self.label_59.setText(_translate("MainWindow", "Kts"))
        self.label_60.setText(_translate("MainWindow", "hPa"))
        self.groupBox_4.setTitle(_translate("MainWindow", "CFDS"))
        self.label_65.setText(_translate("MainWindow", "Universal time coordinated (U.T.C.)"))
        self.label_66.setText(_translate("MainWindow", "Flight phase"))
        self.utc.setToolTip(_translate("MainWindow", "855254AA default"))
        self.label_69.setText(_translate("MainWindow", "BITE Commands"))
        self.label_70.setText(_translate("MainWindow", "DATE"))
        self.label_71.setText(_translate("MainWindow", "Aircraft Identification"))
        self.aircraft_id.setText(_translate("MainWindow", "NORDMIC"))
        self.groupBox_9.setTitle(_translate("MainWindow", "FMS"))
        self.label_82.setText(_translate("MainWindow", "Validity word discrete"))
        self.label_83.setText(_translate("MainWindow", "LFE in feet"))
        self.valid_word_discrete.setToolTip(_translate("MainWindow", "00002097"))
        self.lfe_in_feet.setToolTip(_translate("MainWindow", "60FA0175"))
        self.label_84.setText(_translate("MainWindow", "ft."))
        self.setDefaultButton.setText(_translate("MainWindow", "SET DEFAULT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "CPC 20791 In"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "UUT BITE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "NVM Readout"))
